#!/usr/bin/env ruby
require 'spec_helper'
include Fixtureshelper

describe "Legal Markdown to" do

  describe "Markdown" do
    lmd_files.each do | lmd_file |
      lmd = File.basename(lmd_file)
      it "should correctly parse #{lmd}" do
        benchmark = benchmark_file lmd_file, 'md'
        result = create_temp 'md'
        LegalMarkdown.parse( :to_markdown, lmd_file,  result )
        expect( contents result ).to eql( contents benchmark )
      end
    end
  end

  describe "JSON." do
    lmd_files.each do |lmd_file|
      lmd = File.basename(lmd_file)
      it "should correctly parse #{lmd}" do
        benchmark = benchmark_file lmd_file, 'json'
        result = create_temp 'json'
        LegalMarkdown.parse( :to_json, lmd_file,  result )
        expect( contents benchmark ).not_to eql( contents result )
        expect( (contents benchmark)['nodes'].count ).to eql( (contents result)['nodes'].count )
        expect( (contents benchmark)['nodes']["document"].count ).to eql( (contents result)['nodes']["document"].count )
        expect( (contents benchmark)['nodes']["document"]['title'] ).to eql( (contents result)['nodes']["document"]['title'] )
        expect( (contents benchmark)['nodes']["content"]["nodes"]).not_to eql( (contents result)['nodes']["content"]["nodes"] )
        expect( the_content benchmark ).to eql( the_content result )
      end
    end
  end
end

require 'spec_helper'
include PdfSamplesHelper
include PdfFormsHelper

describe PDF::Reader::PositionOfTextReceiver do
  let(:resource_class) { PDF::Reader::PositionOfTextReceiver }
  let(:reader) { PDF::Reader.new(source) }
  let(:receiver) { resource_class.new }
  let(:options) { test_specifications[:options] || {} }
  let(:page) { 1 }

  context "with invalid or encrypted PDFs" do
    describe '#content' do
      context "New invalid file: not-valid.pdf" do
        let(:source) { pdf_sample( 'encrypted.pdf' ) }
        subject { reader.pages should raise_error PDF::Reader::MalformedPDFError }
        subject { reader.page(page).text should raise_error NoMethodError }
      end
    end
  end

  before do
    reader.page(page).walk(receiver)
  end

  context "with valid Simple PDFs" do
    describe "#content" do
      {
        'junk_prefix.pdf' => {747.384=>{36=>[298.992, "This PDF contains junk before the %-PDF marker"]}},
        'hello_world.pdf' => {747.384=>{36=>[97.824, "Hello World"]}}
      }.each do |sample_file,expected_page_content|
        context "Content for #{sample_file}" do
          let(:source) { pdf_sample(sample_file) }
          subject { receiver.content }
          it { should eql(expected_page_content) }
        end
      end
    end

    describe "#content_blocks_with_sizes" do
      {
        'junk_prefix.pdf' => [["This PDF contains junk before the %-PDF marker", [36, 298.992, 747.384, 759.384], ["Helvetica", "Type1", 12.0]]],
        'hello_world.pdf' => [["Hello World", [36, 97.824, 747.384, 759.384], ["Helvetica", "Type1", 12.0]]]
      }.each do |sample_file,expected_content_blocks|
        context "Content_blocks_with_sizes for #{sample_file}" do
          let(:source) { pdf_sample(sample_file)}
          subject { receiver.content_blocks_with_sizes }
          it { should eql(expected_content_blocks) }
        end
      end
    end
  end

  context "with PDF Forms" do
    describe "#stack_of_fonts" do
      pdf_forms_receiver_expectations.each do |forms_file,expectations|
        context "Content for #{forms_file}" do
          let(:source) { pdf_forms(forms_file) }
          subject { receiver.stack_of_fonts }
          it { should eql(expectations[:test_font_stack]) }
        end
      end
    end

    describe "#content_blocks_with_sizes" do
      pdf_forms_receiver_expectations.each do |forms_file,expectations|
        context "Content for #{forms_file}" do
          let(:source) { pdf_forms(forms_file) }
          subject { receiver.content_blocks_with_sizes }
          it { should eql(expectations[:test_content_blocks_with_sizes])}
        end
      end
    end
  end
end